### ISSUE TITLE
What´s the Output

### ISSUE THREAD

**Issue by asdat3** [octocathell/Note-Scraper#1]
Hey,
is the program still working?
if I get the code correct the output should get into a data.txt or in a csv.
the console is not giving me any output neither any files.
the get_data function isnt getting called to.

This all is no critisism its just me beeing to stupid to get what you´re script is doing
Thanks :)

**Comment by asdat3** [comment]
ok got it, but I am getting blocked :/

**Comment by asdat3** [comment]
![physic](https://user-images.githubusercontent.com/29544382/104734743-9c7aa300-5738-11eb-9538-3889a6b441d8.png)

**Comment by car-mrazomor** [comment]
Please make sure to add proxy option. Site is blocking those kind of activity
